version: '3'

services:
  db:
    container_name: mysql_db
    build:
      context: ./be/mysql
      dockerfile: Dockerfile
    env_file:
      - ./be/mysql/.env
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: