version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    env_file:
      - ./mysql/.env
    ports:
      - "6612:3306"
    volumes:
      - /tmp/mysql-data:/var/run/mysqld
      - ./mysql/db:/var/lib/mysql
  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    env_file:
      - ./django/.env
    volumes:
      - ./django/app:/app
    depends_on:
      - db
      